// This file is generated by FlutterFire CLI
// Run: flutterfire configure
// DO NOT edit this file manually

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace these with your actual Firebase config values
  // Get them from: Firebase Console > Project Settings > Your apps

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'YOUR-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'YOUR-PROJECT-ID',
    authDomain: 'YOUR-PROJECT-ID.firebaseapp.com',
    storageBucket: 'YOUR-PROJECT-ID.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA-XCCxYCMnsNBkAW9NjjrMyn0f9-jqGA',
    appId: '1:334392092099:android:6d0500442eb5ba37ca4976',
    messagingSenderId: '334392092099',
    projectId: 'ro-vending-machine',
    storageBucket: 'ro-vending-machine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Bg80lKNnOnoU7UPCUGpzMuEDw7mFOgM',
    appId: '1:334392092099:ios:89129cd775a90625ca4976',
    messagingSenderId: '334392092099',
    projectId: 'ro-vending-machine',
    storageBucket: 'ro-vending-machine.firebasestorage.app',
    iosClientId: '334392092099-jebvv82i39m9h3monto95jkrqtrq54ps.apps.googleusercontent.com',
    iosBundleId: 'com.rovendingmachine.app',
  );

}